name: Publish Iconsauce Config
on:
  workflow_dispatch:
jobs:
  build:
    name: Build config
    uses: ./.github/workflows/test.yml
  publish:
    needs: [build]
    name: Publish npm
    uses: iconsauce/.github/.github/workflows/publish-npm.yml@main
